### ISSUE TITLE
Import on cron only works when running cron via UI

### ISSUE THREAD

**Issue by AdamGerthel** [oddhill/drupal-import_api#5]
When running imports on cron via drush or equivalent, the batch process that manages the imports are never triggered. This seems to be due to the fact that batch processes can only run in browsers. The code stops at line 42 in ImportService.php:

```
  /**
   * Create a batch for the specified importer.
   *
   * @param ImporterPluginBase $importer
   */
  public function createBatchFor(ImporterPluginBase $importer) {
    $plugin_definition = $importer->getPluginDefinition();

    batch_set([
      'title' => new TranslatableMarkup('Importing: %label', [
        '%label' => $plugin_definition['label'],
      ]),
      'operations' => [
        ['import_api_handle_batch', ['preBatch', $plugin_definition['id']]],
        ['import_api_handle_batch', ['batch', $plugin_definition['id']]],
        ['import_api_handle_batch', ['postBatch', $plugin_definition['id']]],
      ],
      'finished' => 'import_api_batch_finished',
      'file' => drupal_get_path('module', 'import_api') . '/import_api.batch.inc',
    ]);
  }
```
Since the manual import doesn't use the Drupal queueing system, perhaps the above code should be replicated in a non-batch-manner in `processItem` (line 59 in ImportApiQueueWorker.php). That _ought_ to make things work. The `import_api_batch_finished` function will most likely need some modification as well if it's going to be used for cron runs since it relies on `$result` from the batch.

To test-run via CLI:

`drush php-eval 'import_api_cron()'`
`drush queue-run import_api_queue_worker`

**Comment by NormySan** [comment]
I'll test it out when I've got the time :)

**Comment by NormySan** [comment]
This is hopefully fixed in the latest release!
